CREATE SCHEMA IF NOT EXISTS CUSTOMER_CONTACTS_ADMIN;

DROP TABLE IF EXISTS CUSTOMER_CONTACTS_ADMIN.LAST_LOGIN;

CREATE TABLE CUSTOMER_CONTACTS_ADMIN.LAST_LOGIN
(	"TMS_CREATE" TIMESTAMP (6) WITH TIME ZONE,
     "TMS_UPDATE" TIMESTAMP (6) WITH TIME ZONE,
     "AGNT_CREATE" VARCHAR2(160),
     "AGNT_UPDATE" VARCHAR2(160),
     "CD_LAST_LOGIN" NUMBER(22,0) NOT NULL,
     "CD_PROFILE" VARCHAR2(36),
     "CD_CHANNEL" VARCHAR2(10),
     "LOGIN_DATE" TIMESTAMP (6) WITH TIME ZONE

);
ALTER TABLE CUSTOMER_CONTACTS_ADMIN.LAST_LOGIN ADD PRIMARY KEY (CD_LAST_LOGIN);


DROP TABLE IF EXISTS CUSTOMER_CONTACTS_ADMIN.CONTACT;
CREATE TABLE CUSTOMER_CONTACTS_ADMIN.CONTACT
(	"TMS_CREATE" TIMESTAMP (6) WITH TIME ZONE,
     "TMS_UPDATE" TIMESTAMP (6) WITH TIME ZONE,
     "AGNT_CREATE" VARCHAR2(160),
     "AGNT_UPDATE" VARCHAR2(160),
     "CD_EVENT" VARCHAR2(36) NOT NULL,
     "CD_PROFILE" VARCHAR2(36),
     "CD_CLIENT" VARCHAR2(36),
     "CD_SESSION" VARCHAR2(36),
     "CD_TP_BON" NUMBER(36),
     "CD_AGENT" VARCHAR2(36),
     "EVENT_DATE" TIMESTAMP (6) WITH TIME ZONE,
     "RESULT" VARCHAR2(2)
);
ALTER TABLE CUSTOMER_CONTACTS_ADMIN.CONTACT ADD PRIMARY KEY (CD_EVENT);
